2024-03-13 20:57:30,040 INFO    StreamThr :18864 [internal.py:wandb_internal():86] W&B internal server running at pid: 18864, started at: 2024-03-13 20:57:30.039197
2024-03-13 20:57:30,041 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:57:30,046 INFO    WriterThread:18864 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\run-9dw10e2a.wandb
2024-03-13 20:57:30,048 DEBUG   SenderThread:18864 [sender.py:send():380] send: header
2024-03-13 20:57:30,048 DEBUG   SenderThread:18864 [sender.py:send():380] send: run
2024-03-13 20:57:31,042 INFO    SenderThread:18864 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files
2024-03-13 20:57:31,042 INFO    SenderThread:18864 [sender.py:_start_run_threads():1122] run started: 9dw10e2a with start time 1710334650.040197
2024-03-13 20:57:31,061 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:57:31,061 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:57:36,073 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:57:36,088 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:57:36,138 DEBUG   HandlerThread:18864 [system_info.py:__init__():32] System info init
2024-03-13 20:57:36,139 DEBUG   HandlerThread:18864 [system_info.py:__init__():47] System info init done
2024-03-13 20:57:36,139 INFO    HandlerThread:18864 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:57:36,139 INFO    SystemMonitor:18864 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:57:36,139 INFO    HandlerThread:18864 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:57:36,144 INFO    SystemMonitor:18864 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:57:36,144 INFO    SystemMonitor:18864 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:57:36,145 INFO    SystemMonitor:18864 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:57:36,146 INFO    SystemMonitor:18864 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:57:36,163 INFO    SystemMonitor:18864 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:57:36,192 DEBUG   HandlerThread:18864 [system_info.py:probe():196] Probing system
2024-03-13 20:57:36,192 DEBUG   HandlerThread:18864 [system_info.py:probe():244] Probing system done
2024-03-13 20:57:36,192 DEBUG   HandlerThread:18864 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:57:36.192361', 'startedAt': '2024-03-13T12:57:30.026193', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 179.30334854125977}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:57:36,193 INFO    HandlerThread:18864 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:57:36,193 INFO    HandlerThread:18864 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:57:36,193 DEBUG   HandlerThread:18864 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:57:36,193 DEBUG   HandlerThread:18864 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:57:36,194 DEBUG   HandlerThread:18864 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:57:36,208 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:37,089 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\requirements.txt
2024-03-13 20:57:37,089 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\conda-environment.yaml
2024-03-13 20:57:38,239 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:40,268 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:42,302 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:43,115 DEBUG   HandlerThread:18864 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:57:43,117 INFO    HandlerThread:18864 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:57:43,130 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\conda-environment.yaml
2024-03-13 20:57:43,131 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-metadata.json
2024-03-13 20:57:43,137 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:57:43,137 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:57:43,137 DEBUG   SenderThread:18864 [sender.py:send():380] send: files
2024-03-13 20:57:43,137 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:57:43,149 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:57:43,149 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:57:43,150 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:57:44,223 DEBUG   SenderThread:18864 [sender.py:send():380] send: telemetry
2024-03-13 20:57:44,336 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:45,146 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:46,242 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:57:46,369 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:47,165 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:48,405 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:48,925 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:48,926 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:48,926 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:48,927 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:49,195 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:57:50,440 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:50,821 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:50,822 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:50,823 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:50,824 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:50,825 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:50,825 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:50,825 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:50,826 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:51,209 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:51,210 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:57:51,830 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:57:52,468 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:53,215 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:53,473 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:53,474 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:53,474 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:53,475 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:53,731 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA4C7D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:57:53,732 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:57:53,732 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:57:54,221 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:57:54,511 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:55,225 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:55,396 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:55,397 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:55,398 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:55,398 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:55,399 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:55,399 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:55,399 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:55,400 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:56,228 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:57:56,549 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:57,233 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:57:57,408 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:57:58,026 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:58,027 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:58,027 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:58,028 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:58,159 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:57:58,159 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:57:58,160 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:57:58,239 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:57:58,580 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:57:59,897 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:59,898 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:57:59,899 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:59,899 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:59,900 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:57:59,901 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:57:59,901 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:57:59,902 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:00,251 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:00,618 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:01,255 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:02,581 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:02,581 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:02,660 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:02,866 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:02,866 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:02,867 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:03,284 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\config.yaml
2024-03-13 20:58:03,284 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:04,506 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:04,507 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:04,508 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:04,508 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:04,509 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:04,509 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:04,509 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:04,510 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:04,702 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:05,129 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA4869E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:58:05,129 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:58:05,129 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:58:05,304 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:05,305 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:06,790 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:07,222 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:07,223 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:07,223 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:07,224 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:07,309 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:07,310 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:08,232 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:08,820 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:09,139 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:09,140 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:09,141 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:09,141 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:09,142 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:09,142 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:09,142 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:09,143 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:09,329 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:09,329 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:10,341 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:10,850 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:11,770 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:11,771 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:11,771 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:11,772 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:12,367 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:12,368 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:12,879 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:13,175 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:58:13,176 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:58:13,177 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:58:13,460 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:13,655 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:13,655 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:13,656 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:13,657 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:13,657 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:13,658 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:13,658 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:13,659 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:14,384 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:14,385 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:14,908 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:16,273 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:16,274 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:16,274 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:16,275 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:16,404 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:16,405 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:16,928 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:17,521 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA486140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:58:17,521 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:58:17,521 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:58:17,521 INFO    wandb-upload_0:18864 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001F8AA486140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA486140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA486140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:58:18,176 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:18,176 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:18,177 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:18,178 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:18,179 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:18,179 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:18,179 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:18,180 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:18,418 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:18,419 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:18,958 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:19,181 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:20,795 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:20,796 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:20,796 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:20,797 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:20,989 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:21,439 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:22,454 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:22,751 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:22,751 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:22,752 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:22,753 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:22,755 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:22,755 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:22,755 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:22,755 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:23,013 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:23,471 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:24,485 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:24,782 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:25,045 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:25,404 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:25,405 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:25,405 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:25,405 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:25,500 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:26,515 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:27,071 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:27,285 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:27,286 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:27,287 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:27,287 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:27,288 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:27,288 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:27,288 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:27,289 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:27,530 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:28,177 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:58:28,194 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:58:28,194 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:58:28,539 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:29,108 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:29,901 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:29,901 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:29,902 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:29,902 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:29,903 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:30,569 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:30,570 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:31,144 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:31,755 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:31,756 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:31,757 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:31,757 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:31,758 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:31,758 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:31,759 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:31,759 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:31,916 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA486470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:58:31,916 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:58:31,916 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:58:32,603 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:32,604 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:33,184 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:34,388 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:34,389 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:34,389 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:34,390 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:34,620 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:35,209 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:35,398 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:36,193 DEBUG   SystemMonitor:18864 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:58:36,194 DEBUG   SenderThread:18864 [sender.py:send():380] send: stats
2024-03-13 20:58:36,302 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:36,303 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:36,303 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:36,304 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:36,305 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:36,305 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:36,305 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:36,306 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:36,625 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:36,625 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:37,302 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:38,633 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:38,929 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:38,929 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:38,930 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:38,930 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:39,330 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:39,645 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:40,661 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:40,813 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:40,813 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:40,814 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:40,814 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:40,815 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:40,816 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:40,816 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:40,816 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:40,817 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:41,361 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:41,673 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:42,675 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:43,186 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:58:43,202 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:58:43,203 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:58:43,380 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:43,498 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:43,564 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:43,565 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:43,566 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:43,680 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:44,684 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:45,395 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:45,396 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:45,397 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:45,397 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:45,398 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:45,398 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:45,398 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:45,399 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:45,403 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:45,689 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:46,408 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:46,698 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:47,430 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:48,032 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:48,033 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:48,033 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:48,034 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:48,703 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:48,704 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:49,475 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:49,927 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:49,927 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:49,928 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:49,928 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:49,929 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:49,930 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:49,930 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:49,930 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:50,714 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:50,714 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:50,727 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA485150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:58:50,727 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:58:50,727 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:58:51,505 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:51,947 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:52,580 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:52,581 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:52,581 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:52,582 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:52,726 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:53,543 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:54,548 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:54,549 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:54,549 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:54,550 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:54,551 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:54,551 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:54,551 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:54,552 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:54,738 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:54,739 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:55,578 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:56,749 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:57,302 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:58:57,302 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:57,303 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:57,303 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:57,304 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:57,600 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:57,758 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:58:58,201 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:58:58,201 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:58:58,202 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:58:58,770 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:58:59,205 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:59,206 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:58:59,206 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:59,207 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:59,208 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:59,208 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:58:59,208 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:58:59,209 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:58:59,639 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:58:59,783 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:00,797 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:01,685 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:01,837 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:01,838 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:01,838 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:01,839 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:02,825 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:02,826 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:02,840 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:03,717 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:03,761 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:03,761 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:03,762 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:03,763 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:03,763 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:03,764 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:03,764 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:03,765 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:03,830 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:04,844 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:05,753 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:06,199 DEBUG   SenderThread:18864 [sender.py:send():380] send: stats
2024-03-13 20:59:06,384 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:06,385 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:06,385 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:06,386 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:06,852 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:06,853 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:07,844 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:08,254 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:08,255 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:08,255 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:08,256 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:08,257 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:08,257 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:08,258 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:08,258 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:08,259 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:08,860 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:09,876 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:10,881 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:10,918 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:10,919 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:10,919 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:10,920 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:11,883 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:11,900 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:12,827 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:12,828 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:12,829 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:12,829 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:12,830 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:12,830 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:12,830 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:12,831 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:12,888 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:12,889 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:13,206 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:59:13,206 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:59:13,207 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:59:13,576 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:13,937 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:14,908 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:15,581 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:15,582 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:15,582 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:15,583 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:15,924 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:15,961 ERROR   gpu       :18864 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:59:16,925 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:17,493 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:17,494 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:59:17,495 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:17,495 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:17,496 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:17,497 DEBUG   SenderThread:18864 [sender.py:send():380] send: history
2024-03-13 20:59:17,497 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:59:17,497 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:17,645 DEBUG   SenderThread:18864 [sender.py:send():380] send: exit
2024-03-13 20:59:17,645 INFO    SenderThread:18864 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 20:59:17,645 INFO    SenderThread:18864 [sender.py:send_exit():587] handling runtime: 101
2024-03-13 20:59:17,646 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:17,646 INFO    SenderThread:18864 [sender.py:send_exit():593] send defer
2024-03-13 20:59:17,646 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,647 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 20:59:17,647 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,647 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 20:59:17,647 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 1
2024-03-13 20:59:17,647 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,647 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 20:59:17,647 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,647 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 20:59:17,647 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 2
2024-03-13 20:59:17,648 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,648 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 20:59:17,648 INFO    HandlerThread:18864 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 20:59:17,648 DEBUG   SystemMonitor:18864 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 20:59:17,656 DEBUG   SystemMonitor:18864 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 20:59:17,656 INFO    HandlerThread:18864 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 20:59:17,657 INFO    HandlerThread:18864 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 20:59:17,703 INFO    HandlerThread:18864 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 20:59:17,704 INFO    HandlerThread:18864 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 20:59:17,704 INFO    HandlerThread:18864 [interfaces.py:finish():202] Joined network monitor
2024-03-13 20:59:17,705 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,705 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 20:59:17,705 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 3
2024-03-13 20:59:17,705 DEBUG   SenderThread:18864 [sender.py:send():380] send: stats
2024-03-13 20:59:17,705 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,706 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 20:59:17,706 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,706 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 20:59:17,706 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 4
2024-03-13 20:59:17,706 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,706 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 20:59:17,706 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,706 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 20:59:17,706 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 5
2024-03-13 20:59:17,707 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,707 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 20:59:17,707 DEBUG   SenderThread:18864 [sender.py:send():380] send: summary
2024-03-13 20:59:17,708 INFO    SenderThread:18864 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:59:17,708 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,709 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 20:59:17,709 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 6
2024-03-13 20:59:17,709 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,709 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 20:59:17,709 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,709 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 20:59:17,709 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 7
2024-03-13 20:59:17,709 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:17,709 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:17,710 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 20:59:17,710 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:17,710 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 20:59:17,929 INFO    Thread-12 :18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json
2024-03-13 20:59:18,176 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA672290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:18,176 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:59:18,176 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:18,656 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:18,672 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 8
2024-03-13 20:59:18,672 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:18,673 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:18,673 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 20:59:18,673 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:18,673 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 20:59:18,673 INFO    SenderThread:18864 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 20:59:18,674 INFO    SenderThread:18864 [job_builder.py:_get_source_type():404] no source found
2024-03-13 20:59:18,674 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 9
2024-03-13 20:59:18,674 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:18,674 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 20:59:18,674 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:18,675 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 20:59:18,675 INFO    SenderThread:18864 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 20:59:18,945 INFO    SenderThread:18864 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log
2024-03-13 20:59:18,946 INFO    SenderThread:18864 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files
2024-03-13 20:59:18,946 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\conda-environment.yaml conda-environment.yaml
2024-03-13 20:59:18,947 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\config.yaml config.yaml
2024-03-13 20:59:18,949 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\output.log output.log
2024-03-13 20:59:18,951 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\requirements.txt requirements.txt
2024-03-13 20:59:18,954 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-metadata.json wandb-metadata.json
2024-03-13 20:59:18,954 INFO    SenderThread:18864 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_205730-9dw10e2a\files\wandb-summary.json wandb-summary.json
2024-03-13 20:59:18,956 INFO    SenderThread:18864 [sender.py:transition_state():613] send defer: 10
2024-03-13 20:59:18,956 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:59:18,956 INFO    HandlerThread:18864 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 20:59:18,958 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: defer
2024-03-13 20:59:18,958 INFO    SenderThread:18864 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 20:59:18,958 INFO    SenderThread:18864 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 20:59:19,669 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:19,669 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:20,685 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:20,685 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:21,697 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:21,698 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:22,710 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:22,711 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:23,716 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:23,716 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:23,717 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:24,719 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:24,719 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:25,728 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:25,728 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:26,729 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:26,729 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:27,737 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:27,737 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:28,741 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:28,741 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:28,742 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:29,100 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA672C80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:29,100 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:59:29,100 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:29,680 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA670A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:29,680 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA673820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:29,680 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:59:29,681 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '203'}
2024-03-13 20:59:29,681 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:29,681 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:29,754 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:29,754 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:30,161 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA673910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:30,161 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:59:30,161 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:30,275 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA4C5DE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:30,275 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1416'}
2024-03-13 20:59:30,275 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:30,758 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:30,758 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:31,765 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:31,765 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:32,770 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:32,771 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:33,786 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:33,787 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:33,787 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:34,801 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:34,801 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:35,805 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:35,806 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:36,808 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:36,809 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:37,810 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:37,810 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:38,826 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:38,827 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:38,827 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:39,827 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:39,828 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:40,481 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA673580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:40,481 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:59:40,482 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:40,636 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA670B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:40,636 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA673040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:40,636 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '203'}
2024-03-13 20:59:40,637 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:59:40,637 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:40,637 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:40,837 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:40,838 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:41,277 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8A7D38430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:41,277 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA671810>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:41,277 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1416'}
2024-03-13 20:59:41,277 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:59:41,277 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:41,277 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:41,852 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:41,853 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:42,854 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:42,855 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:43,869 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:43,869 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:43,870 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:44,871 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:44,871 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:45,872 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:45,872 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:46,885 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:46,886 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:47,896 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:47,897 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:48,897 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:48,898 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:48,898 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:49,910 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:49,911 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:50,911 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:50,911 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:51,918 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:51,919 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:52,476 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8A7D38D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:52,477 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:59:52,477 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:52,931 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:52,932 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:53,051 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA670A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:53,052 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA6738B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:53,052 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA4C7190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:53,052 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1416'}
2024-03-13 20:59:53,052 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:59:53,052 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '203'}
2024-03-13 20:59:53,053 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:53,053 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:53,053 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:53,316 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA4C6110>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:59:53,316 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:59:53,316 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:59:53,935 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:53,936 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:53,936 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:54,938 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:54,939 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:55,950 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:55,951 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:56,951 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:56,952 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:57,959 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:57,960 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:58,962 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:58,963 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:59:58,963 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:59:59,964 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:59:59,965 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:00,966 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:00,966 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:01,979 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:01,980 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:02,987 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:02,988 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:03,993 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 21:00:03,993 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:03,994 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:05,006 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:05,007 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:06,020 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:06,021 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:07,005 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/requirements.txt?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=UQu0nL6n%2F3Psy5thWEHWZAxaFtczF%2B%2BRbDQDU8pTdS7CLWPdZI%2BBWvF1MUYRNjYXQSc2xLf0QzB%2BA0QSzvZEn8uMrz3P8wu7Tv%2BenvKXQGS1M10nKugCPYRDZhUNwaDiQNLzWm5VEY8IE6qdcFxi%2Ff2ItdDVvA1OXx1j0POI0t3TYN2t38kkSChCMnvyILw4koyYigOXH35%2FKha4MEHudpjLwxyoELb9dwNy0qUOX0lEcDUV4H8K6tfMNzmn2gihyhiX8DWDLcgUnIKaPBASXXi6G20k7%2FUmMtoZBvl48hNN4Azz1IdTjjJllwAXZYj%2Bk%2BkUSJOKtzVEk93DVcLtKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA6738E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,005 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/output.log?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XP9gvbhO4vlgQVLh2Qm9dMgFrot0BLQ%2FXHNpG9w572GNDmKWDHLEhq5upFavU%2B3hZa3i%2BdqNUiS284eKPbZN6uIV3485JIMs8Y5BJyYhcmNgtHqAk9hc0wsAFmC8hKMoUtrs2u%2FVkQWSy2Khw5ndKJpPxSUxlF%2B9hSW5eleEk4qwvt5fkRjYoYD33Q0BDnhxBNNktm1pqgwBWelcFz7MjxcnexIye8TDlcQit38iBM0XjAmmOiYNCY3YdO6UV4g%2FMH7J4pYTptlqrkbI5%2FDMIjrsyPvfvUuTIvrmnJeSRSKMfgngiGyH7r%2BR72TdbueR5M6hFEcI76bX7OCeTibK9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA673640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,005 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/conda-environment.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=g%2BAB73bnB0ePjlkNJhoHEIBC6ejsphUPKmTmTGyh8rXBJJsckRwfXarGfJ1iWOyR22npQYOvUC0qYGahFUxqVzxusYI6RpYUNUScIxaL0Ki%2FMwjGBQxgjAw1C%2BTTC6HCgQXENsaFZecbtnZvgYN98Dcyq4Sbsx6MMUMAwQF1rhn79W0LRiB%2FWeQda74vd7S137J00FITn6RnmiXEFArSKUBsioWSi3Ri9SL84faV1f5PvSvSp9Ns7O6jdzftK2pMW8t4kHqXYHl%2Fd43pPjLAb0%2BdhhJZ4CcKXk%2F7dVSh4HFHRjmb26xjWg7wMDMuKrvjSaAGXPge%2BsMvNzgM80rTIQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA6704F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,005 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 21:00:07,005 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1416'}
2024-03-13 21:00:07,005 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 21:00:07,005 ERROR   wandb-upload_4:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:07,005 ERROR   wandb-upload_3:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:07,005 ERROR   wandb-upload_1:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:07,035 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:07,036 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:07,357 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-summary.json?Expires=1710421162&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IZpqszktzVTgspFyep%2FSAKsrivadhT7MnUKhfbIwBQCOJA9QGcUqwk2qcoQElSg0xwDeunMp%2Fx2LbrJzmmxoOA8VxFzrWtc8T%2FSLuEYPIL1Vx0kzKzHXtneWgoyqn3Fa2d830zjyUwdBR6EpXtOOiGnM2NbgchZPxPpuln9e87FoOMXxpP1I7hwHaOb3i1oYY9z3p7QlXraH9j0Pskh8gVYP6I8RrRzFxwo0tsBfKnXFsH0E7dtOFVZ1wvSNIehzxL6J0FyfvbOX1%2BoLWLBn8poOXqPieIRhB97S6r7ez82Q73ux2kFkBNP6RYqI30zMubW98sDGEx25ecHV8%2BcARA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8AA6739A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,357 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '203'}
2024-03-13 21:00:07,357 ERROR   wandb-upload_5:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:07,516 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/wandb-metadata.json?Expires=1710421066&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=N4OI7UhEZ%2BO8q9xEmZq%2B17LFkRGkAK0cXyuhy2ZdK7xsCgO2nqcMua8EJXM%2Bb%2BmBfBX1SXyRGaRRvt7k1568HDCQ5%2FteDVhoy12qDi74oossRjv9lP4eDmo%2FRxquRc5L1alj3dadEMj45dFK6uEQSaJ%2FHrE7pWH73VCdojpnOZVRgFiXLsbNz%2Fs9c2gLTM4yI8nHOPIi%2FJOaMH1bKFJCthMV%2BgB0JvVUTp5nTCtK2l8JczizY%2FSm4sSYaYRqn7PbaIqPGjLoVLm0w0Fxmi2I0v8XEGUpu1OC2da0CAuF2W8szprcpwWMrfY78oheWgSApzN7byu1sZ2b0n5g46Sh6w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8A7D38A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,516 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 21:00:07,516 ERROR   wandb-upload_0:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:07,579 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/9dw10e2a/config.yaml?Expires=1710421161&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uvyUwr6Y0TcK6oZ0lLFxf1Yc1Eyn3F2gj6ItbaDmyTdeMra%2B6mK6Z6vylSE1bIGcqQt8Li9WJ2GCHh8m%2BOfGfTlc2D4ACtbcJizYubgijBy97CIbQGB%2FqrlkFaMZ1bN5S5RDsRUR1gNFS4XLChu2WBtOlPxkcHLduZjZ%2F53PnO9u%2FOxbDMdMc5OapE4qoZjM%2BsduyGtgDOwtX0cIpII6LjUkOWem2xmBdCBFIcnqyRownqcvlrTD0wAu%2BL3sSO7QS5nYEtekvYLtyNcEMxInFNFE1oXILWX0wYP%2FPGUI%2FzNv%2FfYrPtPl7ZoUq07K%2B9dwB9HkNjXIYVBNHMqUWHZ0WA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8A7D39090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 21:00:07,579 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 21:00:07,579 ERROR   wandb-upload_2:18864 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 21:00:08,035 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:08,035 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:09,038 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 21:00:09,038 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:09,039 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:10,050 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:10,051 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 21:00:11,065 DEBUG   HandlerThread:18864 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 21:00:11,066 DEBUG   SenderThread:18864 [sender.py:send_request():407] send_request: poll_exit
