2024-03-13 20:29:10,830 INFO    StreamThr :29120 [internal.py:wandb_internal():86] W&B internal server running at pid: 29120, started at: 2024-03-13 20:29:10.830288
2024-03-13 20:29:10,832 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:29:10,837 INFO    WriterThread:29120 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\run-2zpn1dpi.wandb
2024-03-13 20:29:10,838 DEBUG   SenderThread:29120 [sender.py:send():380] send: header
2024-03-13 20:29:10,839 DEBUG   SenderThread:29120 [sender.py:send():380] send: run
2024-03-13 20:29:12,021 INFO    SenderThread:29120 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files
2024-03-13 20:29:12,021 INFO    SenderThread:29120 [sender.py:_start_run_threads():1122] run started: 2zpn1dpi with start time 1710332950.830287
2024-03-13 20:29:12,040 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:29:12,040 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:29:15,220 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:29:15,262 DEBUG   HandlerThread:29120 [system_info.py:__init__():32] System info init
2024-03-13 20:29:15,262 DEBUG   HandlerThread:29120 [system_info.py:__init__():47] System info init done
2024-03-13 20:29:15,262 INFO    HandlerThread:29120 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:29:15,262 INFO    SystemMonitor:29120 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:29:15,262 INFO    HandlerThread:29120 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:29:15,268 INFO    SystemMonitor:29120 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:29:15,268 INFO    SystemMonitor:29120 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:29:15,269 INFO    SystemMonitor:29120 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:29:15,270 INFO    SystemMonitor:29120 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:29:15,285 INFO    SystemMonitor:29120 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:29:15,307 DEBUG   HandlerThread:29120 [system_info.py:probe():196] Probing system
2024-03-13 20:29:15,308 DEBUG   HandlerThread:29120 [system_info.py:probe():244] Probing system done
2024-03-13 20:29:15,308 DEBUG   HandlerThread:29120 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:29:15.307557', 'startedAt': '2024-03-13T12:29:10.815632', 'docker': None, 'cuda': None, 'args': ('--task=P', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 178.1230697631836}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:29:15,308 INFO    HandlerThread:29120 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:29:15,308 INFO    HandlerThread:29120 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:29:15,308 DEBUG   HandlerThread:29120 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:29:15,309 DEBUG   HandlerThread:29120 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:29:15,309 DEBUG   HandlerThread:29120 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:29:15,325 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:16,041 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\conda-environment.yaml
2024-03-13 20:29:16,042 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\requirements.txt
2024-03-13 20:29:17,357 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:19,388 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:21,416 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:22,112 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\conda-environment.yaml
2024-03-13 20:29:22,351 DEBUG   HandlerThread:29120 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:29:22,352 INFO    HandlerThread:29120 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:29:22,374 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:22,374 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:29:22,374 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:22,375 DEBUG   SenderThread:29120 [sender.py:send():380] send: files
2024-03-13 20:29:22,375 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:29:22,387 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:29:22,387 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:29:22,388 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:29:23,073 DEBUG   SenderThread:29120 [sender.py:send():380] send: telemetry
2024-03-13 20:29:23,124 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\conda-environment.yaml
2024-03-13 20:29:23,125 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:23,125 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-metadata.json
2024-03-13 20:29:23,439 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:25,150 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:25,489 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:27,121 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:27,519 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:29,557 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:29,999 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:30,001 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:30,001 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:30,002 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:30,188 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:31,190 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:31,586 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:31,925 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:31,925 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:31,926 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:31,926 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:31,927 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:31,928 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:31,928 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:31,928 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:32,195 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:32,944 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:32,963 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D428142650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:29:32,963 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:29:32,963 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:29:33,199 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:33,633 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:35,659 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:36,087 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:36,088 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:36,088 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:36,089 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:36,218 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:37,220 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:37,398 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:29:37,398 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:29:37,398 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:29:37,697 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:37,921 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:37,922 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:37,922 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:37,923 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:37,924 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:37,924 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:37,924 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:37,925 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:38,236 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:38,937 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:39,240 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:39,734 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:41,771 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:42,074 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:42,074 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:42,075 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:42,076 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:42,269 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:43,273 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:43,811 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:43,893 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:43,894 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:43,895 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:43,895 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:43,896 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:43,897 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:43,897 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:43,897 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:44,277 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:44,442 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D428287490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:29:44,442 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:29:44,442 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:29:44,903 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:45,285 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:45,285 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\config.yaml
2024-03-13 20:29:45,891 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:47,912 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:48,052 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:48,053 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:48,053 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:48,055 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:48,309 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:49,322 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:49,893 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:49,894 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:49,894 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:49,895 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:49,895 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:49,896 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:49,896 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:49,897 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:49,948 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:50,338 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:50,907 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:51,353 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:51,972 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:52,415 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:29:52,415 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:29:52,416 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:29:53,990 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:53,991 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:53,991 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:53,992 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:54,006 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:54,400 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:55,405 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:55,843 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:55,844 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:55,844 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:55,845 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:55,846 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:55,846 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:55,846 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:55,847 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:29:56,046 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:56,418 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:29:56,796 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282871C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:29:56,796 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:29:56,797 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:29:56,797 INFO    wandb-upload_0:29120 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D4282871C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282871C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282871C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:29:56,861 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:29:57,419 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:29:58,084 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:29:59,979 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:29:59,980 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:29:59,980 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:29:59,981 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:00,128 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:00,434 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:01,439 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:01,882 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:01,883 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:01,884 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:01,884 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:01,885 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:01,886 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:01,886 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:01,886 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:01,887 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:02,162 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:02,443 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:03,447 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:04,196 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:06,009 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:06,010 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:06,010 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:06,011 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:06,223 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:06,456 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:07,014 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:07,414 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:30:07,415 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:30:07,430 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:30:07,463 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:07,916 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:07,916 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:07,917 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:07,918 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:07,919 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:07,919 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:07,919 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:07,920 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:08,264 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:08,469 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:09,475 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:10,291 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:12,054 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:12,055 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:12,055 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:12,055 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:12,056 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:12,116 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A2740>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:30:12,116 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:30:12,116 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:30:12,331 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:12,490 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:13,493 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:13,928 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:13,928 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:13,929 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:13,929 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:13,930 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:13,931 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:13,931 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:13,931 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:14,365 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:14,496 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:15,304 DEBUG   SystemMonitor:29120 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:30:15,306 DEBUG   SenderThread:29120 [sender.py:send():380] send: stats
2024-03-13 20:30:15,511 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:16,452 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:17,334 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:18,221 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:18,221 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:18,221 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:18,222 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:18,480 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:18,540 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:19,554 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:20,047 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:20,047 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:20,048 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:20,049 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:20,049 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:20,050 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:20,050 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:20,051 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:20,507 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:20,556 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:21,558 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:22,428 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:30:22,428 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:30:22,471 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:30:22,540 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:22,783 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:24,183 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:24,184 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:24,184 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:24,185 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:24,567 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:24,599 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:25,604 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:26,070 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:26,071 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:26,072 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:26,072 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:26,073 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:26,073 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:26,074 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:26,074 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:26,589 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:26,606 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:27,610 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:28,088 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:28,619 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:30,210 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:30,211 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:30,211 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:30,213 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:30,576 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4281078E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:30:30,576 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:30:30,576 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:30:30,627 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:30,643 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:31,630 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:32,106 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:32,107 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:32,107 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:32,108 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:32,109 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:32,109 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:32,109 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:32,110 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:32,665 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:32,683 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:33,114 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:33,674 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:34,719 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:36,261 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:36,261 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:36,261 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:36,262 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:36,732 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:36,752 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:37,436 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:30:37,436 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:30:37,450 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:30:37,736 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:38,087 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:38,088 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:38,089 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:38,089 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:38,090 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:38,090 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:38,091 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:38,091 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:38,767 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:38,783 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:39,101 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:39,782 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:40,816 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:42,210 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:42,211 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:42,211 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:42,212 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:42,847 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:42,856 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:43,860 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:44,048 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:44,049 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:44,050 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:44,050 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:44,051 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:44,051 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:44,051 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:44,052 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:44,886 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:44,902 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:45,065 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:45,306 DEBUG   SenderThread:29120 [sender.py:send():380] send: stats
2024-03-13 20:30:45,895 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:46,984 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:48,189 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:48,190 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:48,190 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:48,191 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:48,948 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:49,011 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:49,964 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:50,108 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:50,108 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:50,109 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:50,109 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:50,110 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:50,111 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:50,111 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:50,111 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:50,112 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:50,992 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:51,047 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:52,007 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:52,438 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:30:52,438 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:30:52,453 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:30:53,080 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:54,258 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:54,259 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:54,259 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:54,260 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:55,068 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:55,111 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:55,262 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:30:56,076 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:56,122 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:56,123 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:30:56,124 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:56,124 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:56,125 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:56,126 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:30:56,126 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:30:56,126 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:30:57,111 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:30:57,139 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:30:57,498 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A2E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:30:57,498 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:30:57,498 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:30:58,121 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:30:59,159 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:00,268 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:00,269 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:00,269 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:00,269 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:00,270 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:01,181 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:01,197 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:02,138 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:02,139 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:02,139 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:02,140 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:02,141 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:02,141 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:02,141 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:02,142 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:02,185 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:02,186 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:03,227 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:04,221 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:05,271 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:06,162 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:06,278 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:06,279 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:06,279 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:06,280 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:07,285 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:07,306 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:07,431 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:31:07,431 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:31:07,445 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:31:08,178 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:08,179 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:08,179 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:08,180 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:08,181 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:08,181 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:08,181 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:08,182 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:08,301 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:08,302 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:09,333 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:10,320 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:11,194 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:11,369 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:12,338 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:12,339 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:12,339 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:12,340 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:12,356 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:13,408 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:14,248 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:14,249 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:14,250 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:14,250 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:14,251 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:14,252 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:14,252 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:14,252 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:14,408 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:14,408 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:15,316 DEBUG   SenderThread:29120 [sender.py:send():380] send: stats
2024-03-13 20:31:15,444 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:16,318 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:16,430 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:17,526 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:18,408 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:18,408 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:18,409 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:18,410 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:18,482 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:19,552 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:20,239 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:20,240 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:20,241 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:20,241 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:20,242 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:20,243 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:20,243 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:20,243 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:20,511 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:20,511 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:21,581 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:22,259 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:22,448 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:31:22,448 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:31:22,449 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:31:22,545 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:23,621 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:24,400 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:24,401 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:24,401 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:24,402 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:24,583 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:25,658 ERROR   gpu       :29120 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:31:26,306 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:26,307 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:31:26,307 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:26,308 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:26,309 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:26,309 DEBUG   SenderThread:29120 [sender.py:send():380] send: history
2024-03-13 20:31:26,309 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:31:26,310 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:26,447 DEBUG   SenderThread:29120 [sender.py:send():380] send: exit
2024-03-13 20:31:26,448 INFO    SenderThread:29120 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 20:31:26,448 INFO    SenderThread:29120 [sender.py:send_exit():587] handling runtime: 131
2024-03-13 20:31:26,448 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:26,449 INFO    SenderThread:29120 [sender.py:send_exit():593] send defer
2024-03-13 20:31:26,449 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,449 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 20:31:26,449 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,449 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 20:31:26,449 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 1
2024-03-13 20:31:26,449 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,449 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 20:31:26,450 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,450 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 20:31:26,450 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 2
2024-03-13 20:31:26,450 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,450 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 20:31:26,450 INFO    HandlerThread:29120 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 20:31:26,450 INFO    HandlerThread:29120 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 20:31:26,450 INFO    HandlerThread:29120 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 20:31:26,458 DEBUG   SystemMonitor:29120 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 20:31:26,458 DEBUG   SystemMonitor:29120 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 20:31:26,499 INFO    HandlerThread:29120 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 20:31:26,499 INFO    HandlerThread:29120 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 20:31:26,500 INFO    HandlerThread:29120 [interfaces.py:finish():202] Joined network monitor
2024-03-13 20:31:26,500 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,501 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 20:31:26,501 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 3
2024-03-13 20:31:26,501 DEBUG   SenderThread:29120 [sender.py:send():380] send: stats
2024-03-13 20:31:26,501 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,501 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 20:31:26,501 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,502 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 20:31:26,502 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 4
2024-03-13 20:31:26,502 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,502 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 20:31:26,502 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,502 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 20:31:26,502 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 5
2024-03-13 20:31:26,502 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,502 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 20:31:26,503 DEBUG   SenderThread:29120 [sender.py:send():380] send: summary
2024-03-13 20:31:26,503 INFO    SenderThread:29120 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:31:26,504 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,504 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 20:31:26,504 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 6
2024-03-13 20:31:26,504 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,504 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 20:31:26,504 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,504 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 20:31:26,505 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 7
2024-03-13 20:31:26,505 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:26,505 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:26,505 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 20:31:26,505 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:26,505 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 20:31:26,613 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:26,614 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json
2024-03-13 20:31:27,463 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:27,622 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 8
2024-03-13 20:31:27,623 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:27,623 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:27,623 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 20:31:27,623 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:27,623 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 20:31:27,623 INFO    SenderThread:29120 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 20:31:27,624 INFO    Thread-12 :29120 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log
2024-03-13 20:31:27,624 INFO    SenderThread:29120 [job_builder.py:_get_source_type():404] no source found
2024-03-13 20:31:27,625 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 9
2024-03-13 20:31:27,625 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:27,625 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 20:31:27,625 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:27,625 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 20:31:27,625 INFO    SenderThread:29120 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 20:31:28,474 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:28,632 INFO    SenderThread:29120 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files
2024-03-13 20:31:28,632 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\conda-environment.yaml conda-environment.yaml
2024-03-13 20:31:28,633 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\config.yaml config.yaml
2024-03-13 20:31:28,635 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\output.log output.log
2024-03-13 20:31:28,637 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\requirements.txt requirements.txt
2024-03-13 20:31:28,639 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-metadata.json wandb-metadata.json
2024-03-13 20:31:28,639 INFO    SenderThread:29120 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202910-2zpn1dpi\files\wandb-summary.json wandb-summary.json
2024-03-13 20:31:28,641 INFO    SenderThread:29120 [sender.py:transition_state():613] send defer: 10
2024-03-13 20:31:28,641 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:28,642 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:31:28,642 INFO    HandlerThread:29120 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 20:31:28,644 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: defer
2024-03-13 20:31:28,644 INFO    SenderThread:29120 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 20:31:28,644 INFO    SenderThread:29120 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 20:31:29,488 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:29,488 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:30,503 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:30,504 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:31,519 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:31,520 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:32,534 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:32,534 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:33,548 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:33,548 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:33,549 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:34,563 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:34,564 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:35,574 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:35,574 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:36,576 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:36,576 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:37,588 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:37,589 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:38,601 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:38,601 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:38,601 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:38,608 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A2890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:38,608 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:31:38,608 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:38,965 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282875E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:38,965 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:31:38,965 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:39,204 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A0F40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:39,204 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1430'}
2024-03-13 20:31:39,204 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:39,550 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A0910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:39,550 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:31:39,550 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:39,563 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A3C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:39,563 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:31:39,563 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:39,616 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:39,616 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:40,618 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:40,619 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:41,626 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:41,627 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:42,637 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:42,638 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:43,369 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-metadata.json?Expires=1710419365&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n5UmoPbkjZRYUrZmqL4cbw%2BK0x29BlaFG5PLfL%2FUggij4pE0KWwwI%2FwgYXTqdXJzy3GgI2ayrVcvGMW0pFpH4k9uAccvSCX49UBcp%2FCHWPPEsKsLa3GIv0pWQiCNUY66apW2xN2C2QqfI3JSZc3YonmgTxMOm1%2BXGiDI%2FxNih5V%2Bj5LnmJREx5BPm3%2Bnu3wxh9mT6636mSqV61SgBMI9RqptLSllshf6SMZPq%2BL1eId1JQ4yW3C0sY02MGrXADhfpoKWC1x9JkT8YFWARqNCAtqVFqe4UWK4cATu9AqnIK9KBrsKbZWIOMvNdMHYJkdNOIeHX4g9qoIqWrqvEu09jQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A28C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:43,369 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1318'}
2024-03-13 20:31:43,369 ERROR   wandb-upload_0:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:43,640 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:43,640 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:43,641 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:44,644 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:44,644 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:45,645 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:45,645 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:46,659 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:46,660 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:47,670 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:47,671 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:48,675 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:48,675 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:48,675 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:49,690 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:49,690 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:49,809 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A2920>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:49,809 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:31:49,809 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:50,261 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A3400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:50,261 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1430'}
2024-03-13 20:31:50,261 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:50,423 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4259502B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:50,423 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4259500D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:50,423 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:31:50,423 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:31:50,423 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:50,424 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:50,433 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A1960>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:31:50,433 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:31:50,433 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:31:50,705 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:50,705 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:51,711 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:51,711 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:52,717 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:52,718 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:53,733 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:53,733 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:53,733 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:54,738 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:54,739 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:55,751 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:55,752 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:56,762 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:56,763 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:57,775 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:57,776 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:58,777 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:31:58,777 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:58,778 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:31:59,784 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:31:59,785 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:00,799 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:00,799 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:01,802 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:01,803 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:02,361 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A10C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:02,361 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A01F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:02,362 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A3FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:02,362 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:32:02,362 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1430'}
2024-03-13 20:32:02,362 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:32:02,362 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:02,362 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:02,362 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:02,374 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A3D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:02,374 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:32:02,374 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:02,476 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A3130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:02,476 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:32:02,476 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:02,817 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:02,818 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:03,831 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:03,832 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:32:03,832 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:04,836 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:04,837 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:05,850 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:05,851 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:06,865 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:06,865 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:07,876 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:07,877 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:08,878 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:32:08,879 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:08,879 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:09,892 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:09,893 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:10,896 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:10,896 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:11,912 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:11,913 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:12,914 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:12,914 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:13,920 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:13,921 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:32:13,921 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:14,921 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:14,921 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:15,937 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:15,937 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:16,568 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/config.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rQISfuZhWJJboiVmNKR5NnyEujmfubGK93uEt7Jt4%2FQAF%2Ffh%2F1wfxFlcgJhjJ%2BrhoTgLO7NgiAtXJ%2FIbcCvVXSMPowzAgRa6tK671%2BRArNaBZUzSHsWW7tVrjivAGUHBaTrVs24xScoXqZKxJYUjz84pi0p97F9rEFuy2d2zWEcr40N%2F8WadBq8eJcrihsGEGt6%2BOKajJSvOk5nilYGHvtR22GOb0DDMxyFQS%2FrWN52gFHgrAAFgeNiaUezkwmjEpDIbTEdYUI3FBNjcFImQU70%2FceUFHvOZiVi89pqBAcuEgtNXNlbfMVY3iveXZcg2y%2FXKlsKYjiuG%2Fazx1vdOtw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D425950730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:16,568 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:32:16,568 ERROR   wandb-upload_2:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:16,938 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/output.log?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QimgwB%2B4D%2Bl6RxV%2FaEuUCLOEJxcLYRE4iTd5Kr0tgyIqpvn%2FybKVweyYGEfQMQXEp4GmrpagCAseoqJdcauFCHUz0trXYY1%2F23Hw%2Bkv17%2FwazXUxdx4GPEpPb6u3R2KZjVaG%2FAHHzZrPh%2FJwNAnY7P%2B7OgGLhjMvmfYYZTBY35qoWPlU81QdkVa3hlMSEsHp0s1UpdDokWB2U5ysN1pNJYAYZcesQYcZIXzaSAM1ZW%2FI49LABEaE5hDXvebCFNRdFNuQ4X7bLDmPStkWZEWGnVhkWunWPrscrh6kgWdQlDLNkfxhT1Lj%2F1bycDehxqlgIwxj9LK4dh0TEpNodoILEw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D428287250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:16,938 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1430'}
2024-03-13 20:32:16,938 ERROR   wandb-upload_3:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:16,940 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:16,940 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:32:17,196 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/conda-environment.yaml?Expires=1710419491&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=du5uB6ABe1ncR1UkmLlrPFiumLksxHsDl8iH1X9WJOTDxuMaYSys70TjrLedf1K7%2FHALgyc9Y2jN8pwK4mWmvsapb6o8s2ykKQGkazcU5BvPDVrMzrC4ZzdN3V7TNJMhv21wUK%2Fj%2FlmIojUHc28i0TGZ68ATfcP8lXFjeAuGxmkC1Ucy3hhzuPcbAMsnjcUVJZsCamcMq9eH%2BdT5Brk49sIuxe%2BWKf1xM3pUHQibDWcn1AX9Qt2EWmZ6IcxF%2BRSE5KyXvPLy%2FIIdFlyRNPQup%2B3pj1u9VZTHJj%2FEi2FQBu%2FZPrte41gbn2HWFCsyenLRObm0QvxAC9E%2Bd1J2RngvVg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D425951030>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:17,197 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/wandb-summary.json?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VwZRRgJpIpyPMCtAA07xv0alU8fmutO1dSADAU84QubLaGoB2xSlMKVyCpsE362OTjPnBnuFlLZIsiIw6HYib1I8%2BM%2BCPa0DrMxkby%2Fj7a6PNjjTwMwnunJRpSCNTWesR6%2BhuWjFkbaq9rx7DWq3x9EVJdTfzuLqjtWfSwyIJbPQqHvgtEXGAmH78vKLFL92dfcRva6ptub7hexOmRu8fWymahjhuAhvMvThN558vd5DDiqj%2FW2kRUm8Txrfdu%2Bolw1jwJZtBCuP%2BILwLtFMFJe6eWlRbc7JT9EADlJDiyriDxzq8w%2BD6thpLXNN3kVy21UFEurYcIcgj3tf8YhSCw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4282A05E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:17,197 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:32:17,197 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:32:17,197 ERROR   wandb-upload_1:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:17,197 ERROR   wandb-upload_5:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:17,850 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/2zpn1dpi/requirements.txt?Expires=1710419492&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ISUQ0nu4nwxYfCjciVpGc3VEluamsOnLuxSHRPrXBmjkJluaYrD5zyPVWWis837bgvYqwpZ51KPMDkRSbQSW6gmQ%2F7ltlRJASocf9C%2FY6gYKfVsTZbh5qMQCh9%2BNaNGZJsgome34WoVmMYqgaSvCQEtdPEBaX2XPoZV5Nhet1Xu2T4aksD%2BNS4YXBtXGYhVqWA1usCb3sYy%2FnhdIfKCndn53CNM6K7l7SZh0E0GClj9TE2EE0LeiCRvuF0Xu%2F1W7kJt%2F91N8FDr%2BBWsuYYh5RbbyqFZyW%2BNHs9aGv7BbtYPVzyqxaqpXwivah6VjiJ7WDWz2ypmAnxOdHIowsTTNeQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D425950C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:32:17,850 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:32:17,850 ERROR   wandb-upload_4:29120 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:32:17,948 DEBUG   HandlerThread:29120 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:32:17,948 DEBUG   SenderThread:29120 [sender.py:send_request():407] send_request: poll_exit
