2024-03-13 15:56:55,873 INFO    StreamThr :5848 [internal.py:wandb_internal():86] W&B internal server running at pid: 5848, started at: 2024-03-13 15:56:55.872517
2024-03-13 15:56:55,874 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status
2024-03-13 15:56:55,879 INFO    WriterThread:5848 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\run-n6xira7r.wandb
2024-03-13 15:56:55,881 DEBUG   SenderThread:5848 [sender.py:send():380] send: header
2024-03-13 15:56:55,881 DEBUG   SenderThread:5848 [sender.py:send():380] send: run
2024-03-13 15:56:57,297 INFO    SenderThread:5848 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files
2024-03-13 15:56:57,297 INFO    SenderThread:5848 [sender.py:_start_run_threads():1122] run started: n6xira7r with start time 1710316615.873517
2024-03-13 15:56:57,316 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 15:56:57,317 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: check_version
2024-03-13 15:56:59,785 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 15:56:59,828 DEBUG   HandlerThread:5848 [system_info.py:__init__():32] System info init
2024-03-13 15:56:59,829 DEBUG   HandlerThread:5848 [system_info.py:__init__():47] System info init done
2024-03-13 15:56:59,829 INFO    HandlerThread:5848 [system_monitor.py:start():181] Starting system monitor
2024-03-13 15:56:59,829 INFO    SystemMonitor:5848 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 15:56:59,829 INFO    HandlerThread:5848 [system_monitor.py:probe():201] Collecting system info
2024-03-13 15:56:59,834 INFO    SystemMonitor:5848 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 15:56:59,835 INFO    SystemMonitor:5848 [interfaces.py:start():190] Started disk monitoring
2024-03-13 15:56:59,835 INFO    SystemMonitor:5848 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 15:56:59,836 INFO    SystemMonitor:5848 [interfaces.py:start():190] Started memory monitoring
2024-03-13 15:56:59,864 INFO    SystemMonitor:5848 [interfaces.py:start():190] Started network monitoring
2024-03-13 15:56:59,873 DEBUG   HandlerThread:5848 [system_info.py:probe():196] Probing system
2024-03-13 15:56:59,874 DEBUG   HandlerThread:5848 [system_info.py:probe():244] Probing system done
2024-03-13 15:56:59,874 DEBUG   HandlerThread:5848 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T07:56:59.874559', 'startedAt': '2024-03-13T07:56:55.859515', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 175.89456939697266}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 15:56:59,874 INFO    HandlerThread:5848 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 15:56:59,874 INFO    HandlerThread:5848 [system_monitor.py:probe():214] Publishing system info
2024-03-13 15:56:59,874 DEBUG   HandlerThread:5848 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 15:56:59,875 DEBUG   HandlerThread:5848 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 15:56:59,875 DEBUG   HandlerThread:5848 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 15:56:59,894 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:00,317 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\requirements.txt
2024-03-13 15:57:00,317 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\conda-environment.yaml
2024-03-13 15:57:01,925 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:03,960 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:06,003 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:06,819 DEBUG   HandlerThread:5848 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 15:57:06,820 INFO    HandlerThread:5848 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 15:57:06,839 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:06,840 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 15:57:06,840 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:06,840 DEBUG   SenderThread:5848 [sender.py:send():380] send: files
2024-03-13 15:57:06,840 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 15:57:06,851 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:57:06,852 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:57:06,853 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:57:07,349 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\conda-environment.yaml
2024-03-13 15:57:07,349 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-metadata.json
2024-03-13 15:57:07,517 DEBUG   SenderThread:5848 [sender.py:send():380] send: telemetry
2024-03-13 15:57:08,043 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:08,365 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:10,088 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:10,376 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:12,127 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:12,503 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:12,504 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:12,505 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:12,505 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:12,506 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:13,389 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:14,176 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:14,348 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:14,349 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:14,349 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:14,350 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:14,351 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:14,351 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:14,351 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:14,352 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:14,395 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:14,396 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:16,208 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:16,417 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:16,982 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:16,983 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:16,983 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:16,984 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:17,350 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34633610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:57:17,350 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:57:17,351 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:57:17,434 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:17,987 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:18,239 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:18,448 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:18,818 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:18,819 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:18,820 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:18,820 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:18,821 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:18,821 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:18,822 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:18,822 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:19,452 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:20,277 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:20,455 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:21,410 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:21,411 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:21,411 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:21,412 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:21,460 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:21,859 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:57:21,859 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:57:21,860 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:57:22,316 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:23,211 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:23,285 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:23,286 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:23,286 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:23,287 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:23,288 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:23,289 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:23,289 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:23,289 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:23,466 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:24,357 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:24,470 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:25,902 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:25,903 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:25,903 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:25,904 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:26,395 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:26,477 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:27,798 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:27,799 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:27,799 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:27,800 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:27,800 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:27,801 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:27,801 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:27,801 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:28,420 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:57:28,420 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:57:28,420 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:57:28,434 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:28,483 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:28,484 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:28,805 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:29,489 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\config.yaml
2024-03-13 15:57:30,379 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:30,380 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:30,380 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:30,381 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:30,508 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:30,509 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:30,531 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:32,215 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:32,216 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:32,216 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:32,217 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:32,218 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:32,218 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:32,218 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:32,219 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:32,509 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:32,510 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:32,557 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:34,234 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:34,522 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:34,590 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:34,825 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:34,826 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:34,826 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:34,827 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:35,526 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:36,564 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:36,610 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:36,780 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:36,781 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:36,782 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:36,783 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:36,784 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:36,785 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:36,785 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:36,786 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:36,847 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:57:36,862 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:57:36,863 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:57:37,568 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:38,603 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:38,643 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:39,439 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:39,439 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:39,440 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:39,440 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:39,441 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:39,610 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:40,649 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:40,670 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:41,172 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822BC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:57:41,173 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:57:41,173 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:57:41,173 INFO    wandb-upload_0:5848 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017B34822BC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822BC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822BC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 15:57:41,303 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:41,303 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:41,304 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:41,305 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:41,305 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:41,306 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:41,306 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:41,307 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:41,653 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:42,705 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:43,685 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:43,941 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:43,942 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:43,942 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:43,943 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:44,716 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:44,736 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:44,956 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:45,722 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:45,844 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:45,844 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:45,845 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:45,846 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:45,846 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:45,847 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:45,847 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:45,848 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:46,752 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:46,769 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:47,766 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:48,631 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:48,632 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:48,632 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:48,633 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:48,787 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:48,804 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:49,797 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:50,565 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:50,566 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:50,566 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:50,567 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:50,568 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:50,568 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:50,569 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:50,569 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:50,570 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:50,819 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:50,842 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:51,824 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:51,855 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:57:51,887 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:57:51,887 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:57:52,882 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:53,320 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:53,321 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:53,321 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:53,322 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:53,865 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:53,866 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:54,916 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:55,220 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:55,221 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:55,222 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:55,222 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:55,223 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:55,223 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:55,224 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:55,224 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:55,359 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B346DAB60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:57:55,360 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:57:55,360 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:57:55,904 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:55,904 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:57:56,235 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:57:56,953 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:57,909 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:57,910 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:57,910 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:57,910 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:57,948 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:58,998 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:57:59,860 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:59,860 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:57:59,861 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:59,862 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:59,862 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:59,863 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:57:59,863 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:57:59,864 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:57:59,867 DEBUG   SystemMonitor:5848 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 15:57:59,868 DEBUG   SenderThread:5848 [sender.py:send():380] send: stats
2024-03-13 15:57:59,980 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:57:59,981 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:01,079 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:01,891 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:02,018 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:02,530 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:02,531 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:02,531 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:02,532 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:03,039 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:03,112 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:04,054 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:04,479 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:04,480 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:04,481 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:04,481 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:04,482 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:04,482 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:04,483 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:04,483 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:05,079 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:05,133 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:06,086 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:06,860 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:58:06,893 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:58:06,893 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:06,893 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:58:07,163 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:07,177 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:07,255 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:07,255 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:07,256 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:08,125 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:08,126 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:09,173 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:09,174 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:09,174 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:09,175 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:09,175 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:09,176 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:09,176 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:09,177 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:09,193 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:10,154 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:10,155 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:11,214 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:11,855 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:11,856 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:11,856 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:11,857 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:12,200 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:12,871 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:13,238 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:13,803 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:13,804 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:13,805 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:13,805 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:13,806 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:13,807 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:13,807 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:13,808 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:13,959 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34821060>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:13,959 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:58:13,959 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:14,220 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:14,221 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:15,278 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:16,271 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:16,481 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:16,482 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:16,482 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:16,482 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:17,301 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:17,318 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:18,317 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:18,450 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:18,450 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:18,451 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:18,452 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:18,452 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:18,453 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:18,454 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:18,454 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:18,454 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:19,343 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:19,359 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:20,351 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:21,105 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:21,105 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:21,106 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:21,106 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:21,388 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:21,398 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:21,865 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:58:21,911 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:58:21,912 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:58:22,404 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:23,031 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:23,031 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:23,032 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:23,033 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:23,034 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:23,034 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:23,034 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:23,035 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:23,430 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:23,449 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:24,038 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:24,435 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:25,485 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:25,695 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:25,696 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:25,696 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:25,697 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:26,469 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:27,523 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:27,680 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:27,681 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:27,682 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:27,682 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:27,683 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:27,684 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:27,684 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:27,685 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:28,505 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:28,506 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:29,560 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:29,698 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:29,874 DEBUG   SenderThread:5848 [sender.py:send():380] send: stats
2024-03-13 15:58:30,390 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:30,390 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:30,391 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:30,391 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:30,544 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:30,545 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:31,647 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:32,275 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:32,276 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:32,277 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:32,277 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:32,278 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:32,278 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:32,278 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:32,279 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:32,592 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:32,593 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:33,677 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:34,627 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:34,958 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:34,958 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:34,959 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:34,959 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:34,960 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:35,664 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:35,703 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:36,666 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:36,818 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:36,818 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:36,819 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:36,820 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:36,821 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:36,821 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:36,821 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:36,822 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:36,869 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:58:36,915 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:58:36,916 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:58:37,705 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:37,726 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:38,707 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:39,508 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:39,509 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:39,509 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:39,510 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:39,733 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:39,766 ERROR   gpu       :5848 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:58:40,514 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:40,738 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:41,448 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:41,449 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:58:41,450 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:41,450 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:41,451 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:41,451 DEBUG   SenderThread:5848 [sender.py:send():380] send: history
2024-03-13 15:58:41,452 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:58:41,452 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:41,459 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34821BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:41,459 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:58:41,459 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:41,617 DEBUG   SenderThread:5848 [sender.py:send():380] send: exit
2024-03-13 15:58:41,617 INFO    SenderThread:5848 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 15:58:41,617 INFO    SenderThread:5848 [sender.py:send_exit():587] handling runtime: 101
2024-03-13 15:58:41,618 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:41,618 INFO    SenderThread:5848 [sender.py:send_exit():593] send defer
2024-03-13 15:58:41,619 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,619 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 15:58:41,619 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,619 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 15:58:41,619 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 1
2024-03-13 15:58:41,619 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,620 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 15:58:41,620 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,620 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 15:58:41,620 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 2
2024-03-13 15:58:41,620 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,620 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 15:58:41,620 INFO    HandlerThread:5848 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 15:58:41,620 DEBUG   SystemMonitor:5848 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 15:58:41,628 DEBUG   SystemMonitor:5848 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 15:58:41,629 INFO    HandlerThread:5848 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 15:58:41,630 INFO    HandlerThread:5848 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 15:58:41,679 INFO    HandlerThread:5848 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 15:58:41,679 INFO    HandlerThread:5848 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 15:58:41,679 INFO    HandlerThread:5848 [interfaces.py:finish():202] Joined network monitor
2024-03-13 15:58:41,680 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,680 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 15:58:41,680 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 3
2024-03-13 15:58:41,681 DEBUG   SenderThread:5848 [sender.py:send():380] send: stats
2024-03-13 15:58:41,681 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,681 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 15:58:41,681 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,681 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 15:58:41,681 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 4
2024-03-13 15:58:41,682 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,682 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 15:58:41,682 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,682 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 15:58:41,682 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 5
2024-03-13 15:58:41,682 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,682 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 15:58:41,683 DEBUG   SenderThread:5848 [sender.py:send():380] send: summary
2024-03-13 15:58:41,683 INFO    SenderThread:5848 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:58:41,684 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,684 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 15:58:41,684 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 6
2024-03-13 15:58:41,684 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,684 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 15:58:41,684 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,685 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 15:58:41,685 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 7
2024-03-13 15:58:41,685 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:41,685 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,685 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 15:58:41,685 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,685 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 15:58:41,749 INFO    Thread-12 :5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json
2024-03-13 15:58:41,954 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 8
2024-03-13 15:58:41,954 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,954 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 15:58:41,954 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,954 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 15:58:41,954 INFO    SenderThread:5848 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 15:58:41,955 INFO    SenderThread:5848 [job_builder.py:_get_source_type():404] no source found
2024-03-13 15:58:41,955 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 9
2024-03-13 15:58:41,955 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:41,955 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 15:58:41,956 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:41,956 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 15:58:41,956 INFO    SenderThread:5848 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 15:58:42,627 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:42,755 INFO    SenderThread:5848 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log
2024-03-13 15:58:42,756 INFO    SenderThread:5848 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files
2024-03-13 15:58:42,757 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\conda-environment.yaml conda-environment.yaml
2024-03-13 15:58:42,757 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\config.yaml config.yaml
2024-03-13 15:58:42,760 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\output.log output.log
2024-03-13 15:58:42,762 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\requirements.txt requirements.txt
2024-03-13 15:58:42,764 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-metadata.json wandb-metadata.json
2024-03-13 15:58:42,764 INFO    SenderThread:5848 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155655-n6xira7r\files\wandb-summary.json wandb-summary.json
2024-03-13 15:58:42,767 INFO    SenderThread:5848 [sender.py:transition_state():613] send defer: 10
2024-03-13 15:58:42,767 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:42,767 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:58:42,767 INFO    HandlerThread:5848 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 15:58:42,769 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: defer
2024-03-13 15:58:42,769 INFO    SenderThread:5848 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 15:58:42,769 INFO    SenderThread:5848 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 15:58:43,633 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:43,633 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:44,648 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:44,649 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:45,655 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:45,656 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:46,660 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:46,661 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:47,662 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:47,663 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:48,668 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:48,668 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:49,679 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:49,679 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:50,681 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:50,681 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:50,681 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:51,690 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:51,691 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:52,520 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B346D9960>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:52,520 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:58:52,520 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:52,694 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:52,694 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:53,119 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B348236A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:53,119 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B346D9690>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:53,119 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:58:53,119 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 15:58:53,119 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:53,120 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:53,340 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B348221D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:53,340 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34823B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:58:53,340 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1401'}
2024-03-13 15:58:53,340 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 15:58:53,340 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:53,340 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:58:53,696 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:53,697 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:54,698 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:54,698 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:55,701 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:58:55,701 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:55,702 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:56,708 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:56,709 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:57,717 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:57,718 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:58,718 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:58,719 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:58:59,730 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:58:59,730 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:00,736 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:00,737 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:00,737 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:01,739 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:01,739 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:02,755 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:02,755 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:03,029 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34820A00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:03,029 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:59:03,029 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:03,767 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:03,768 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:04,077 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822320>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:04,077 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE8400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:04,077 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34820F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:04,077 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B348207F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:04,077 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1401'}
2024-03-13 15:59:04,078 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 15:59:04,078 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:59:04,078 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 15:59:04,078 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:04,078 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:04,078 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:04,078 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:04,782 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:04,782 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:05,783 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:05,783 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:05,784 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:06,796 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:06,797 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:07,811 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:07,812 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:08,823 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:08,824 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:09,837 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:09,838 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:10,842 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:10,843 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:10,843 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:11,848 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:11,848 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:12,850 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:12,851 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:13,855 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:13,856 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:14,859 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:14,860 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:15,224 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34684A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:15,224 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:59:15,224 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:15,864 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:15,864 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:15,864 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:16,159 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:16,160 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34823520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:16,160 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:16,160 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34820040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:16,160 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1401'}
2024-03-13 15:59:16,160 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:59:16,160 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 15:59:16,160 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 15:59:16,160 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:16,161 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:16,161 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:16,161 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:16,868 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:16,869 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:17,869 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:17,870 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:18,884 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:18,885 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:19,899 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:19,899 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:20,909 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:20,910 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:20,911 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:21,923 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:21,924 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:22,937 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:22,938 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:23,739 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-metadata.json?Expires=1710403030&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uBVPSrPXlH3inY%2BFHaA14DG5ykjzQaHIS%2BjxqzY10DApMRP7IrgS9GdB663rBV4r1HVoSWFZVOnU3tFDKDPcv7J%2Bf4gxm8zrTOUMW9LppUnDHKcMKBfncPnEdHM2CpeC84tR5re4L5zGdK98sZgWwFuuHXg0FPP%2BDQvhM4aQ7zXIx7tYBxRo6gNPafWxVgv%2F01sjxZrM0%2FeLDaJs9%2FGRYSJhkd4caglFhkaKdCrlwdNCFgpIqIiyyI%2FFgq%2BNXIp8uH6BYSRVw8pz1jlNJJejp%2FXGtWd3wgfXeLXoNMiyyYLJLCe048tILWDCpqQtDtr7wkv9eOc%2BxElU%2FoGdxii8Dg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822110>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:23,739 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:59:23,739 ERROR   wandb-upload_0:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:23,951 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:23,952 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:24,958 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:24,958 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:25,961 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:25,961 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:25,962 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:26,969 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:26,969 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:27,982 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:27,983 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:28,984 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:28,985 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:29,339 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34847310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:29,339 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:59:29,339 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:29,929 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B346D9360>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:29,929 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE8B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:29,929 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1401'}
2024-03-13 15:59:29,930 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B346D94E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:29,930 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 15:59:29,930 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:29,930 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:59:29,930 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:29,930 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:29,992 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:29,993 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:30,697 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE8BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:30,697 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 15:59:30,697 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:30,994 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:30,995 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:30,995 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:32,005 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:32,006 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:33,008 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:33,009 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:34,015 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:34,016 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:35,029 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:35,030 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:36,039 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:36,040 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:36,041 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:37,041 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:37,041 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:38,046 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:38,047 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:39,060 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:39,061 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:40,066 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:40,067 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:41,068 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:41,069 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:41,069 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:42,070 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:42,071 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:43,071 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:43,072 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:44,075 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:44,075 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:45,075 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:45,076 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:46,082 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:46,083 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:46,083 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:47,092 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:47,092 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:48,106 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:48,106 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:49,117 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:49,118 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:49,739 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34823FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:49,739 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:59:49,739 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:50,118 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:50,118 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:50,740 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B348210C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:50,740 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:59:50,740 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:51,126 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:51,127 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:51,127 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:51,579 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34684FA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:51,579 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/output.log?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cB%2FyFn%2B1vfcAt%2FziSpOBkolie0ekDAMX9CKzuswZ7iHk0UVDa1dWT19kCHUeZwN0ErZj4GZ6LRrNU9AYgSiPxTAwAO7ztdf45eE6WSJ1NTZptiSGygjDnh6SeQfSLYuQu5%2B6Ox9TqJ0fDRn7QzR4UDBXTsToXn91Var0YTo914rlXEDIisYO6W2ODMbwvWE9jduIfaaz2LA5OTZxWZVJwvqkCQOz%2F8oWDTOwZlNONtbKomFEbzKGRRaGM196irbW3Og3Kdl1yqN6vmgCG3iSoGzpCxbQYi1gJka%2F8tHhd1DC66JQG%2BO%2BqvI0q6Tk96H6hKWC1FxIkE6Q%2FMaD8%2B51DA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B34822080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:51,579 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 15:59:51,580 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1401'}
2024-03-13 15:59:51,580 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:51,580 ERROR   wandb-upload_3:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:52,132 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:52,133 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:52,839 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/wandb-summary.json?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jd3a79Q2F8hYToq7I0%2BETimdMjnAwuaYYluT4wA6EdUuk2aIpX%2B645JPqAHZ9NcI9NafLSaX2ZAy14eRZhkWZbcqHDBarc4LGsrXfIVW0PpA12zsXGHSDsCAD5cTxa3C7nZ4OiKNBwaa2QUl%2FGneg4XZXeMEaU3O3j%2FWgZfTBgktrB%2BwWOPbpoZ32RRlNmUBLMqOLB6Bum%2F96pCON7OG9nAruPC9y4tgyIKY56xR%2Fv9SL3nAHB0kBwo7IWgWodOa5s8rC7xaQGs3YTNERgpfdRohZRYmNpW24IcAS7kvM6NJazmHwfJ4VvGxWEMtCC1v%2BfSn8u%2BQiiiUDX7VuYp2Zw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE8EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:59:52,839 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 15:59:52,839 ERROR   wandb-upload_5:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:59:53,137 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:53,138 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:54,138 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:54,138 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:55,147 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:55,147 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:56,154 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:56,155 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:59:56,155 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:57,158 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:57,158 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:58,170 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:58,171 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:59:59,177 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:59:59,178 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:00,179 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:00,180 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:01,185 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:00:01,186 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:01,186 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:02,187 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:02,187 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:03,189 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:03,189 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:04,195 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:04,196 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:05,200 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:05,201 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:06,207 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:06,207 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:00:06,208 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:07,213 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:07,214 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:08,218 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:08,218 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:09,223 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:09,223 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:10,224 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:10,224 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:11,228 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:00:11,228 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:11,229 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:12,230 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:12,230 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:13,231 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:13,231 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:14,239 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:14,239 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:15,253 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:15,254 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:16,267 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:16,268 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:00:16,268 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:17,269 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:17,269 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:18,270 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:18,271 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:19,281 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:19,282 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:20,296 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:20,297 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:21,310 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:00:21,310 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:21,310 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:00:21,384 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/requirements.txt?Expires=1710403126&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=h8DQ66VpgCBFrZh%2Fp8qvRlTNhojtjCt7ZoGgFeEa3J6Ncz%2F22duKFrMXe%2F5Ue5fhWSb2vd8nIZ5k72kNggbjq%2BkaBAzWHiT%2BYLOOuZoNI7Z%2FlrjiKlUfEWVQQzXv6zxBGt6uzTupEBNxjxhw0fdO%2FTcdsv6xp0tviIzBGAHwTrVgv5gacHz42RdamTRVdwHy5tOGP8POiwrclr7ayQWEDkntkeCI5cfZUgTh28kGNU0dYzL3Usye%2F%2BPLH0UuZ1Kk6a5rlds35FAZCadot6eHvb%2FgitbAVsHCCDZQBsYsM7DbTrQy1qm6Xhe4ndSLD4gxS90LNRPKo4ZS2PaiI7yepQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE98D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:00:21,384 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/conda-environment.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wo2QtX8Z3DtyyVB%2FAQf0sptCZn5ZXYl%2BmhbmkEAnk8qiwLrufNQx8AV1kbUYd6g53V0gpoATgOBhplQYV%2FJX01NZVnWu2roTROuQgdeomG3LYlwSG10ydLQXBzrNv1MmWSb6ZOlbR0GXEo8%2BZxozqFrr2rpYBmxU%2BWNgZy%2FtACn4idCzi3lfkiCrwXVBAnwI3lA%2F9RvxPjClYoJyFsBnzIlF3jnBAg6hTsGliqTzxGg8moTEvF%2F2PYRxjsvBq2WncNIAJm6Hnufxaoa7oJslezpMNNOheNU6TWcsac4Jg0RtcBCSMNuZQY1sdjl21HVs93kGU%2BHiGKSEYU62WwY88g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE8460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:00:21,384 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 16:00:21,384 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 16:00:21,385 ERROR   wandb-upload_4:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:00:21,385 ERROR   wandb-upload_1:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:00:22,019 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/n6xira7r/config.yaml?Expires=1710403125&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xN2%2FFD2u%2BGUswJyHQb%2BqfJLB13dddncsQ3HWKkemX1bqqjkJ%2FBYpzMd%2Ft4QzmZIG2TeoAwO6LV9kAe%2FBIzoRuniSbJ8YvQfPaxkeihV%2B6bVv0v7uJ43NffH0ohLDG9NvB3yiUXh9rTwhSfrIi6lImTi45BGFIns5bxVj2YVBvqCKurs3tW7eXOkMmgrBcGH6ovnqvkPDSEAKV%2Fo1cmqHjgg18irrWzbef0E57RjDVtQ49BzOMyrDVLZl0lUi6QZN1tYc02m%2BaW4N4JMyUX74ouSn5m31us%2FCeAroNhPTj9K67Ir50SXNptY2X16RfVsO0EHcG7fy8D%2Brn6BnZ392Sg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017B31EE9CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:00:22,019 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 16:00:22,020 ERROR   wandb-upload_2:5848 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:00:22,324 DEBUG   HandlerThread:5848 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:00:22,325 DEBUG   SenderThread:5848 [sender.py:send_request():407] send_request: poll_exit
