2024-03-13 15:52:57,331 INFO    StreamThr :29428 [internal.py:wandb_internal():86] W&B internal server running at pid: 29428, started at: 2024-03-13 15:52:57.330558
2024-03-13 15:52:57,333 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status
2024-03-13 15:52:57,338 INFO    WriterThread:29428 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\run-857g7d8m.wandb
2024-03-13 15:52:57,339 DEBUG   SenderThread:29428 [sender.py:send():380] send: header
2024-03-13 15:52:57,339 DEBUG   SenderThread:29428 [sender.py:send():380] send: run
2024-03-13 15:52:58,337 INFO    SenderThread:29428 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files
2024-03-13 15:52:58,337 INFO    SenderThread:29428 [sender.py:_start_run_threads():1122] run started: 857g7d8m with start time 1710316377.33155
2024-03-13 15:52:58,355 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 15:52:58,355 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: check_version
2024-03-13 15:53:02,402 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:02,416 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 15:53:02,468 DEBUG   HandlerThread:29428 [system_info.py:__init__():32] System info init
2024-03-13 15:53:02,468 DEBUG   HandlerThread:29428 [system_info.py:__init__():47] System info init done
2024-03-13 15:53:02,468 INFO    HandlerThread:29428 [system_monitor.py:start():181] Starting system monitor
2024-03-13 15:53:02,468 INFO    SystemMonitor:29428 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 15:53:02,468 INFO    HandlerThread:29428 [system_monitor.py:probe():201] Collecting system info
2024-03-13 15:53:02,474 INFO    SystemMonitor:29428 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 15:53:02,475 INFO    SystemMonitor:29428 [interfaces.py:start():190] Started disk monitoring
2024-03-13 15:53:02,475 INFO    SystemMonitor:29428 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 15:53:02,476 INFO    SystemMonitor:29428 [interfaces.py:start():190] Started memory monitoring
2024-03-13 15:53:02,506 INFO    SystemMonitor:29428 [interfaces.py:start():190] Started network monitoring
2024-03-13 15:53:02,516 DEBUG   HandlerThread:29428 [system_info.py:probe():196] Probing system
2024-03-13 15:53:02,516 DEBUG   HandlerThread:29428 [system_info.py:probe():244] Probing system done
2024-03-13 15:53:02,517 DEBUG   HandlerThread:29428 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T07:53:02.516272', 'startedAt': '2024-03-13T07:52:57.316554', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 175.76356506347656}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 15:53:02,517 INFO    HandlerThread:29428 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 15:53:02,517 INFO    HandlerThread:29428 [system_monitor.py:probe():214] Publishing system info
2024-03-13 15:53:02,517 DEBUG   HandlerThread:29428 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 15:53:02,518 DEBUG   HandlerThread:29428 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 15:53:02,518 DEBUG   HandlerThread:29428 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 15:53:02,529 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:03,378 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\requirements.txt
2024-03-13 15:53:03,378 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\conda-environment.yaml
2024-03-13 15:53:04,570 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:06,606 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:08,638 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:09,998 DEBUG   HandlerThread:29428 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 15:53:09,999 INFO    HandlerThread:29428 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 15:53:10,019 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:10,019 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 15:53:10,020 DEBUG   SenderThread:29428 [sender.py:send():380] send: files
2024-03-13 15:53:10,020 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 15:53:10,031 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:53:10,031 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:53:10,033 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:53:10,418 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\conda-environment.yaml
2024-03-13 15:53:10,418 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-metadata.json
2024-03-13 15:53:10,671 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:10,833 DEBUG   SenderThread:29428 [sender.py:send():380] send: telemetry
2024-03-13 15:53:11,426 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:12,707 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:12,850 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:13,447 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:14,738 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:16,675 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:16,675 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:16,676 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:16,677 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:16,774 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:17,482 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:18,697 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:18,807 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:19,056 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:19,057 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:19,058 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:19,058 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:19,059 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:19,059 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:19,060 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:19,060 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:19,502 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:19,502 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:20,579 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C03FD5780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:53:20,580 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:53:20,580 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:53:20,836 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:21,510 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:21,661 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:21,662 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:21,662 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:21,663 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:22,514 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:22,883 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:23,484 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:23,485 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:23,486 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:23,486 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:23,487 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:23,487 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:23,487 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:23,488 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:23,520 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:23,520 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:24,492 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:24,924 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:25,035 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:53:25,035 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:53:25,036 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:53:25,532 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:26,078 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:26,079 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:26,079 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:26,080 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:26,539 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:26,963 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:27,540 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:27,957 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:27,958 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:27,959 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:27,959 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:27,960 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:27,960 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:27,960 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:27,961 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:28,556 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:28,988 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:29,559 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:29,977 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:30,541 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:31,022 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:31,569 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C0402AA70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:53:31,569 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:53:31,569 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:53:32,406 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:32,406 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:33,111 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:35,007 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:35,130 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:35,384 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:35,384 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:35,385 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:35,386 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:35,386 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:35,387 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:35,387 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:35,387 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:35,388 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:35,388 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:35,389 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:35,389 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:35,576 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:35,577 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\config.yaml
2024-03-13 15:53:36,910 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:36,911 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:36,911 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:36,912 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:36,913 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:36,913 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:36,913 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:36,914 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:37,154 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:37,584 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:37,584 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:39,178 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:39,497 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:39,498 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:39,498 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:39,499 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:39,602 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:39,602 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:40,045 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:53:40,045 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:53:40,046 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:53:40,456 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:41,221 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:41,414 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:41,415 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:41,415 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:41,416 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:41,417 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:41,417 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:41,417 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:41,418 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:41,631 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:41,632 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:43,261 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:43,580 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04114370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:53:43,580 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:53:43,580 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:53:43,580 INFO    wandb-upload_0:29428 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000022C04114370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04114370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04114370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 15:53:43,640 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:44,001 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:44,001 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:44,002 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:44,002 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:44,645 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:45,286 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:45,653 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:45,877 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:45,877 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:45,878 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:45,879 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:45,879 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:45,880 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:45,880 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:45,881 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:45,881 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:46,667 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:47,320 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:47,674 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:48,519 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:48,520 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:48,520 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:48,521 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:48,677 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:49,357 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:49,690 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:50,533 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:50,534 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:50,534 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:50,536 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:50,536 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:50,537 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:50,537 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:50,538 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:50,693 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:51,394 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:51,552 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:51,697 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:53,283 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:53,284 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:53,284 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:53,286 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:53,429 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:53,700 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:55,043 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:53:55,044 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:53:55,060 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:53:55,234 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:55,235 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:55,412 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:55,413 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:55,414 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:55,415 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:55,415 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:55,415 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:55,475 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:55,726 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:55,727 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:57,432 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:53:57,509 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:57,588 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04087580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:53:57,589 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:53:57,589 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:53:57,757 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:57,950 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:57,950 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:57,951 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:57,951 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:58,759 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:53:59,550 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:53:59,768 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:53:59,826 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:59,827 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:53:59,827 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:59,828 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:59,829 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:53:59,829 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:53:59,829 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:53:59,830 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:00,779 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:01,594 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:01,792 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:02,506 DEBUG   SystemMonitor:29428 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 15:54:02,508 DEBUG   SenderThread:29428 [sender.py:send():380] send: stats
2024-03-13 15:54:02,508 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:02,563 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:02,564 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:02,564 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:02,564 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:02,803 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:03,680 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:03,813 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:04,523 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:04,524 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:04,525 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:04,525 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:04,526 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:04,526 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:04,527 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:04,527 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:04,815 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:05,706 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:05,828 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:07,232 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:07,233 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:07,233 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:07,234 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:07,729 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:07,841 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:08,239 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:09,059 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:09,059 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:09,060 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:09,061 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:09,062 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:09,062 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:09,062 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:09,063 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:09,750 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:09,846 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:09,847 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:10,051 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:54:10,052 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:54:10,068 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:54:11,687 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:11,687 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:11,688 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:11,688 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:11,770 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:11,849 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:11,850 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:13,487 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:13,487 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:13,488 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:13,489 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:13,489 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:13,490 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:13,490 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:13,490 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:13,491 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:13,809 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:13,859 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:13,860 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:15,706 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04063850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:15,707 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:54:15,707 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:15,859 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:15,869 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:16,147 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:16,148 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:16,148 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:16,149 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:16,877 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:17,883 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:17,903 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:18,272 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:18,273 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:18,274 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:18,274 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:18,276 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:18,276 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:18,276 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:18,277 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:18,893 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:19,291 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:19,913 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:19,932 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:21,082 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:21,082 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:21,083 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:21,083 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:21,953 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:21,954 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:21,971 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:23,026 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:23,027 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:23,028 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:23,028 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:23,029 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:23,029 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:23,029 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:23,030 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:23,992 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:23,992 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:24,009 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:25,048 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:25,064 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:54:25,065 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:54:25,080 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:54:25,773 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:25,774 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:25,774 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:25,775 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:26,036 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:26,053 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:27,716 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:27,717 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:27,718 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:27,718 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:27,719 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:27,719 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:27,720 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:27,720 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:28,079 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:28,080 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:28,095 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:30,126 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:30,144 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:30,386 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:30,386 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:30,387 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:30,387 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:30,388 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:31,140 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:32,168 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:32,187 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:32,322 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:32,322 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:32,323 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:32,324 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:32,324 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:32,325 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:32,325 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:32,326 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:32,521 DEBUG   SenderThread:29428 [sender.py:send():380] send: stats
2024-03-13 15:54:33,176 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:34,212 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:34,281 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:35,022 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:35,023 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:35,023 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:35,024 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:35,214 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:36,037 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:36,308 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:36,902 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:36,903 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:36,903 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:36,904 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:36,905 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:36,905 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:36,905 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:36,906 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:37,247 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:37,248 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:38,333 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:39,286 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:39,567 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:39,568 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:39,568 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:39,568 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:40,076 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 15:54:40,077 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: stop_status
2024-03-13 15:54:40,092 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 15:54:40,312 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:40,364 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:41,317 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:41,444 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:41,468 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:41,469 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:41,470 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:41,470 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:41,471 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:41,471 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:41,471 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:41,472 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:42,349 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:42,388 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:43,355 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:44,082 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:44,083 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:44,083 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:44,084 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:44,382 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:44,418 ERROR   gpu       :29428 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 15:54:44,539 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C040636D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:44,539 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:54:44,539 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:45,399 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:46,016 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:46,017 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 15:54:46,018 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:46,018 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:46,019 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:46,019 DEBUG   SenderThread:29428 [sender.py:send():380] send: history
2024-03-13 15:54:46,020 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: summary_record
2024-03-13 15:54:46,020 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:46,161 DEBUG   SenderThread:29428 [sender.py:send():380] send: exit
2024-03-13 15:54:46,161 INFO    SenderThread:29428 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 15:54:46,161 INFO    SenderThread:29428 [sender.py:send_exit():587] handling runtime: 103
2024-03-13 15:54:46,162 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:46,162 INFO    SenderThread:29428 [sender.py:send_exit():593] send defer
2024-03-13 15:54:46,162 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,162 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 15:54:46,163 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,163 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 15:54:46,163 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 1
2024-03-13 15:54:46,163 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,163 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 15:54:46,163 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,163 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 15:54:46,163 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 2
2024-03-13 15:54:46,163 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,163 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 15:54:46,163 INFO    HandlerThread:29428 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 15:54:46,164 DEBUG   SystemMonitor:29428 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 15:54:46,171 DEBUG   SystemMonitor:29428 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 15:54:46,172 INFO    HandlerThread:29428 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 15:54:46,172 INFO    HandlerThread:29428 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 15:54:46,214 INFO    HandlerThread:29428 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 15:54:46,214 INFO    HandlerThread:29428 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 15:54:46,214 INFO    HandlerThread:29428 [interfaces.py:finish():202] Joined network monitor
2024-03-13 15:54:46,215 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,215 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 15:54:46,215 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 3
2024-03-13 15:54:46,216 DEBUG   SenderThread:29428 [sender.py:send():380] send: stats
2024-03-13 15:54:46,216 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,216 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 15:54:46,216 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,216 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 15:54:46,216 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 4
2024-03-13 15:54:46,216 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,216 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 15:54:46,217 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,217 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 15:54:46,217 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 5
2024-03-13 15:54:46,217 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,217 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 15:54:46,218 DEBUG   SenderThread:29428 [sender.py:send():380] send: summary
2024-03-13 15:54:46,218 INFO    SenderThread:29428 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 15:54:46,219 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,219 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 15:54:46,219 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 6
2024-03-13 15:54:46,219 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,219 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 15:54:46,219 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,220 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 15:54:46,220 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 7
2024-03-13 15:54:46,220 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:46,220 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:46,220 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 15:54:46,220 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:46,220 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 15:54:46,401 INFO    Thread-12 :29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json
2024-03-13 15:54:47,166 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:47,260 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 8
2024-03-13 15:54:47,261 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:47,261 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:47,261 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 15:54:47,261 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:47,261 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 15:54:47,261 INFO    SenderThread:29428 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 15:54:47,262 INFO    SenderThread:29428 [job_builder.py:_get_source_type():404] no source found
2024-03-13 15:54:47,262 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 9
2024-03-13 15:54:47,262 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:47,262 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 15:54:47,262 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:47,263 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 15:54:47,263 INFO    SenderThread:29428 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 15:54:47,419 INFO    SenderThread:29428 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log
2024-03-13 15:54:47,419 INFO    SenderThread:29428 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files
2024-03-13 15:54:47,419 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\conda-environment.yaml conda-environment.yaml
2024-03-13 15:54:47,420 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\config.yaml config.yaml
2024-03-13 15:54:47,422 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\output.log output.log
2024-03-13 15:54:47,425 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\requirements.txt requirements.txt
2024-03-13 15:54:47,427 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-metadata.json wandb-metadata.json
2024-03-13 15:54:47,427 INFO    SenderThread:29428 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_155257-857g7d8m\files\wandb-summary.json wandb-summary.json
2024-03-13 15:54:47,429 INFO    SenderThread:29428 [sender.py:transition_state():613] send defer: 10
2024-03-13 15:54:47,429 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: defer
2024-03-13 15:54:47,430 INFO    HandlerThread:29428 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 15:54:47,431 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: defer
2024-03-13 15:54:47,431 INFO    SenderThread:29428 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 15:54:47,431 INFO    SenderThread:29428 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 15:54:48,167 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:48,168 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:49,172 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:49,172 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:50,187 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:50,187 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:51,198 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:51,199 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:52,213 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:52,214 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:53,224 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:53,224 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:53,225 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:54,234 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:54,235 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:55,237 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:55,238 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:56,239 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:56,239 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:57,239 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C040619C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:57,239 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04060310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:57,240 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:54:57,240 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 15:54:57,240 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:57,240 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:57,247 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:57,248 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:57,812 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04087010>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:57,812 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1419'}
2024-03-13 15:54:57,812 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:57,813 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C040297B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:57,814 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04063EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:54:57,814 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:54:57,814 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '207'}
2024-03-13 15:54:57,814 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:57,814 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:54:58,251 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:54:58,251 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:58,252 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:54:59,256 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:54:59,257 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:00,259 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:00,260 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:01,267 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:01,267 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:02,268 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:02,268 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:03,282 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:03,282 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:03,282 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:04,284 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:04,285 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:05,295 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:05,295 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:06,296 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:06,296 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:07,301 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:07,301 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:08,080 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04061630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:08,080 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:55:08,080 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:08,307 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:08,308 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:08,308 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:08,700 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C040627D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:08,700 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04063A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:08,700 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 15:55:08,700 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1419'}
2024-03-13 15:55:08,701 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:08,701 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:09,019 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04061BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:09,019 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C018A8040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:09,019 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '207'}
2024-03-13 15:55:09,020 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:55:09,020 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:09,020 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:09,312 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:09,312 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:10,313 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:10,314 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:11,313 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:11,314 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:12,329 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:12,330 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:13,334 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:13,335 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:13,335 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:14,350 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:14,351 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:15,353 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:15,354 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:16,366 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:16,367 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:17,379 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:17,380 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:18,392 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:18,392 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:18,392 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:19,397 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:19,398 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:20,299 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C0402AA70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:20,299 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:55:20,299 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:20,410 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:20,411 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:20,919 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C040622F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:20,919 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04029150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:20,919 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04063B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:20,919 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '207'}
2024-03-13 15:55:20,920 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 15:55:20,920 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1419'}
2024-03-13 15:55:20,920 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:20,920 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:20,920 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:21,135 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04061630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:21,135 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:55:21,135 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:21,423 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:21,423 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:22,436 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:22,436 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:23,445 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:23,445 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:23,445 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:24,459 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:24,459 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:25,462 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:25,463 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:26,470 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:26,471 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:27,471 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:27,472 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:28,486 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:28,486 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:28,487 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:28,939 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-metadata.json?Expires=1710402793&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HcQYhIP7mU7knEvUXbN8u68a1gAlG8TitKTnz4miOewGufwvxAMGOE6IplcSL2gFlRPsiX3vqhsYLZPfZNotQ1lC8%2BPc6Umpjd0f0SbjYjunO7%2BO0JwakILjmEaldPzGXNpKDG6UaLhYha%2Bu72a8jebn90JEfI74H3MTUnRIvBd2mfjFX%2Fp0Ho7BPzWMIYx9B2FKcFWVLXRX3in%2FTrcT%2FAChy6sPeoEOOBz0JnY73QzJg0m6PJDAUBOrvAhyRkWM5%2FeiiIuJ1RThi3%2B8UI6zVxK6tRvH94D3bkldvj%2BP8t%2F86d5hmFFIVQUvE0S29IrRQuvpGT8%2FpyOc1zDOaDeG7A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04062F20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:28,939 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 15:55:28,939 ERROR   wandb-upload_0:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:29,500 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:29,501 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:30,503 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:30,503 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:31,505 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:31,505 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:32,519 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:32,520 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:33,525 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:33,525 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:33,526 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:34,531 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:34,532 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:35,319 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/conda-environment.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ftfyq0gUGVywxtsZhr1E1gKk6kTmVMbTW6cctZmlSzJ3m8ntKP4xZOj4Vaw1qmMklalIF%2FWYpZ9qBl03FpIk1ty8IznrS9yEih11HJe3oESsd7TT%2FH%2B%2F5j%2FbeIQ99nGoYOlFZ7gdsO%2F3WlmXWuOWI4l5Dzs9diz3RFly4qSIKmU43eUQgeryAiD3Gkj2fkaa4tuorREqPtBXklPnxANpohGKd%2BK%2BBtvcii1zA2eAvSv%2BM%2Bl%2Fu0ZOt%2Bkw%2FC5jBI1ypSN%2FnW5GsPkPD3l5x4j6dm%2BqXutWA145v4MNgVBbSw9WvjPujatoFKfV36aLI2QsyUpzYisWPsus5t4TZizuSA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04062290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:35,319 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 15:55:35,320 ERROR   wandb-upload_1:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:35,544 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:35,545 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:35,940 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/output.log?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=I3zQQ43ETktXBZ2x99%2FXYqbeHcJTJ0Jy9tN4edY2tEoUnuusrLcMwTFJRgsZImcWM2b3OtGbJD9iHFfvyn7rfeEGFXmENBSJPOXkiL5Rd24gPHLKoiM5fxGnLoHELNXdqlcxhwKIm4xFxkZ2lC8wHMvlf3VE%2BDcL4Sj%2Fph2O%2B0Cfq%2Fyg8FgLIMgzkx4VbmvX%2BT78nG689QuD7cfg8YOL5qE5uFW2M6thr2F%2FmZdrpgx7bNaHsJZ4720uoVq3hxYvaRClPFQjKo64GcFYxDpbdr98V8FKlVhIUw3BIy0joDqkKw6xXPCrkTYZqX%2FrcEax9noAMKWk35npgb9R0KnWbQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C018A82B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:35,940 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/wandb-summary.json?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NrRaY6zzb7wUf65ySdJWXsiORHHmsGfZtM8dgInvC4sQWwmq1BwgcrI4WLfitavzy4986sy5jnx6m1z5Tm5CO5iUfLnFqaZqO5Q3eJxJhracBLnGukzGy0CBDswY4%2FfCkZl2b0ciILKY3erUd19LlPYEQtaIrU9ebgp7ExcBk%2FHLCaJZBFjATTivz2t0FX3kDUignbBpxKA1A%2BLRU4DWKNogza2QpOdQXzChAvYvDD4c0sFaRP8y1lavkFxIJtQAJnvn5xr6UrolFDyuFa51Tuglgt%2FdFX2xUXdqjE1oynKoqx2Bdvrt2hvcKekRYG5gxR8IOb8cTg9%2BiqHjnQb%2BGg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04061A80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:35,940 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1419'}
2024-03-13 15:55:35,940 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '207'}
2024-03-13 15:55:35,940 ERROR   wandb-upload_3:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:35,940 ERROR   wandb-upload_5:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:36,560 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/config.yaml?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U8lhKE6TVLeOfrTxgpeuFjA3KVWLqAM8NTUu39lb6hl7fSkwBoVzAQXLa09KvwgcR63udv%2BeKzR%2F7IDPiV9uSqcNgaoCUelsgBfDX%2FyDIZ6mizsJ43%2BPoAF0PyjDLHx6jR7iJ0CLqWYwhV2SjC4gP5Ib3utIzB7%2BrUkIDLqwkt%2Fh1XFez%2FC3q7FoIoAxdNqI95dveE0KXhTk9VShE66BzJcLWhUfn2Q3dy9nEZ8CUUv0GreBQSg%2BuN%2F2sF8qe8wskZRY85DEQsWUeoWxm3WXIN0qRoXOwk4vk9Dpaun1se2rl0xce8hZ0UzJDLDrC7DSO0P56CyGZJ06gPCGbJFgUw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C018A89D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:36,560 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/857g7d8m/requirements.txt?Expires=1710402890&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=f1MgHs7y8bvhFKEWpG3akivsdfKcX9ttPSVPIfy%2BQMRp2ziFXnPpOuHJajaEDKI8lPkkkO4btiUIG%2FfJ132TIMNQb2rlWBBJlNa7ul61hamBWoWldpaYFn%2FOTRabwAKJsTP71iYOaqF%2B3P6pn28EJjEowRFBNQOsGheUVcfj3tSPcw80soMw3W7r8tec%2F%2BmbX%2By69eNy3unSHsknHvDtP9y6ZX9gJ02Fz7giiAAIhsBNb%2FSa%2BjtsEs8hIMOr66m8kivX%2FjDnkqu%2BgHQQjucMHSuN0NGQ7CGVQ3dExohVa71F%2F3NPqWJoCEOgTlUYFphosLUdyjF1y5NRsio66wmOkA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022C04060370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 15:55:36,560 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 15:55:36,561 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:36,561 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 15:55:36,561 ERROR   wandb-upload_2:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:36,561 ERROR   wandb-upload_4:29428 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 15:55:36,561 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:37,569 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:37,570 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:38,577 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:38,578 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:38,578 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:39,587 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:39,588 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:40,599 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:40,600 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:41,599 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:41,599 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:42,606 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:42,606 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:43,610 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:43,611 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:43,611 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:44,614 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:44,615 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:45,615 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:45,615 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:46,617 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:46,617 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:47,630 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:47,631 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:48,636 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 15:55:48,636 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:48,637 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:49,643 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:49,643 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 15:55:50,657 DEBUG   HandlerThread:29428 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 15:55:50,657 DEBUG   SenderThread:29428 [sender.py:send_request():407] send_request: poll_exit
